name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
      - deployment/docker-compose/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run docker compose
        run: docker compose -f infra.yml up -d

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: ./mvnw -ntp verify
